version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BASE_URL=http://localhost:3333
      - VITE_ROUTE_PUT=false
    depends_on:
      - backend
  backend:
    environment:
      - "PORT=8080"
      - "DB_HOST=database"
      - "DB_USER=root"
      - "DB_PASSWORD=password"
      - "DB_NAME=mydb"
    env_file:
      - .env
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - database
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
