version: '3.7'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_BASE_URL=http://localhost:3333
      - VITE_ROUTE_PUT=false
    depends_on:
      - backend
  backend:
    command: dev
    environment:
      - "PORT=8080"
      - "DB_HOST=database"
      - "DB_USER=root"
      - "DB_PASSWORD=password"
      - "DB_NAME=mobee"
    env_file:
      - .env
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mobee
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
